services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest@sha256:2426a3c58564fd3a95c3c1e5118312c4af2f3c87ebde9b7615a4caa36c183fe6
    container_name: LibreChat-API
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: /root/librechat/librechat.yaml
        target: /app/librechat.yaml
      - /root/librechat/images:/app/client/public/images
      - /root/librechat/uploads:/app/uploads
      - /root/librechat/logs:/app/api/logs
    networks:
      - proxy_net
      - internal_net

  mongodb:
    container_name: chat-mongodb
    image: mongo:8.0.17@sha256:9814652e33f0cf8b9fddea8b46dfc9d8e19b130dcfdd7b510ca58bb0d40c8b71
    restart: always
    volumes:
      - /root/librechat/data-node:/data/db
    command: mongod --noauth
    networks:
      - internal_net

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3@sha256:4acfcbbb9e089aa1aac838cfda3fba7f07aaaef044c23da8acbe0ab741400dac
    restart: always
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - /root/librechat/meili_data_v1.12:/meili_data
    networks:
      - internal_net

  vectordb:
    image: pgvector/pgvector:0.8.7-pg15-trixie@sha256:8d4485d6fd3156d090ac5f37eb2e22eb59d93c91169414d5809414102ee924b9
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - internal_net

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest@sha256:a62ce2221b43a9bb57fa6cb733e7047c80132960272c33d5704028f3071a1251
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
    networks:
      - internal_net

volumes:
  pgdata2:

networks:
  proxy_net:
    external: true
  internal_net:
    driver: bridge
