services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    volumes:
      - ./stirling-data:/configs
    restart: unless-stopped
    environment:
      - SECURITY_ENABLELOGIN=false
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
