services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest@sha256:b5b9e400c086e5334a4947a0d7cd589808f743f29267d7f41c18200cf4bc48b4
    container_name: stirling-pdf
    volumes:
      - ./stirling-data:/configs
    restart: unless-stopped
    environment:
      - SECURITY_ENABLELOGIN=false
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
