services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped

    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    environment:
      TZ: "Asia/Singapore"

      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - /root/npmauth/data:/data
      - /root/npmauth/letsencrypt:/etc/letsencrypt

    networks:
      - proxy_net

  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v5
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy_net

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    restart: unless-stopped
    env_file: .env
    volumes:
      - "/root/npmauth/pocketid/data:/app/data"
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
